
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 09 07:56:42 COT 2015
//----------------------------------------------------

package compiladorconjuntos;

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Feb 09 07:56:42 COT 2015
  */
public class AnalizadorSintaco extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSintaco() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintaco(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintaco(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\002\000\002\002\004\000\002\002\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\005\000\004\004\004\001\002\000\004\010\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\000\001\002" +
    "\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\005\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintaco$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintaco$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintaco$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void report_error(String mensaje, Object info) {
       	StringBuffer m = new StringBuffer("error");
		System.out.println("Mensaje: "+mensaje);
		System.out.println("info: "+info.toString());
		if(info instanceof java_cup.runtime.Symbol) {
			java_cup.runtime.Symbol s=((java_cup.runtime.Symbol)info);
			/* Comprueba si el numero de línea es mayor o igual que cero */
			if(s.left >= 0) {
				m.append(" en linea "+(s.left+1));
				/*Comprueba si el numero de columna es mayoro igual que cero */
				if (s.right >= 0)
					m.append(", y columna "+(s.right+1));
			}
		}
		m.append(" : "+mensaje);
		System.err.println(m);
    }
    public void report_fatal_error(String message, Object info) {
       	report_error(message, info);
        System.out.println("error fatal");
	System.exit(1);
    }
    public void unir(Object a, Object b){
    System.out.println("hola");
    }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSintaco$actions {
  private final AnalizadorSintaco parser;

  /** Constructor */
  CUP$AnalizadorSintaco$actions(AnalizadorSintaco parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintaco$do_action(
    int                        CUP$AnalizadorSintaco$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintaco$parser,
    java.util.Stack            CUP$AnalizadorSintaco$stack,
    int                        CUP$AnalizadorSintaco$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintaco$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintaco$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= sentencia EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintaco$stack.elementAt(CUP$AnalizadorSintaco$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintaco$stack.elementAt(CUP$AnalizadorSintaco$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintaco$stack.elementAt(CUP$AnalizadorSintaco$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintaco$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintaco$stack.elementAt(CUP$AnalizadorSintaco$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintaco$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintaco$parser.done_parsing();
          return CUP$AnalizadorSintaco$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // sentencia ::= LETRA FINLINEA 
            {
              Object RESULT =null;
		System.out.print("mensajeputo");
              CUP$AnalizadorSintaco$result = parser.getSymbolFactory().newSymbol("sentencia",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintaco$stack.elementAt(CUP$AnalizadorSintaco$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintaco$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintaco$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

