
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 09 07:56:42 COT 2015
//----------------------------------------------------

package compiladorconjuntos;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 3;
  public static final int LETRA = 2;
  public static final int FINLINEA = 6;
  public static final int error = 1;
  public static final int FINC = 5;
  public static final int UNION = 7;
  public static final int INICIO = 4;
  public static final int EOF = 0;
}

