
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 10 13:06:13 COT 2015
//----------------------------------------------------

package compiladorconjuntos;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 2;
  public static final int FINLINEA = 5;
  public static final int error = 1;
  public static final int FINC = 4;
  public static final int UNION = 6;
  public static final int ELEMENTO = 7;
  public static final int INICIO = 3;
  public static final int EOF = 0;
}

